var type_names={A:{icon:"新",name:"新番組"},
B:{icon:"終",name:"最終回"},
C:{icon:"再",name:"再放送"},
D:{icon:"S",name:"ステレオ放送"},
E:{icon:"字",name:"字幕放送"},
F:{icon:"二",name:"二ヶ国語放送"},
G:{icon:"多",name:"音声多重放送"},
H:{icon:"手",name:"手話通訳放送"},
I:{icon:"デ",name:"番組連動データ放送"},
J:{icon:"双",name:"双方向放送"},
K:{icon:"HV",name:"ハイビジョン放送"},
L:{icon:"N",name:"ニュース"},
M:{icon:"天",name:"天気予報"},
N:{icon:"B",name:"圧縮Bモードステレオ"},
O:{icon:"生",name:"生放送"},
P:{icon:"SS",name:"サラウンドステレオ"}};